### ISSUE TITLE
Add run exports

### ISSUE THREAD

**Issue by wolfv** [conda-forge/libcint-feedstock#1]
Hi @BastianZim sorry, I missed that during the initial review. 

I think you should add run_exports to this package so that other (downstream) users of libcint have the proper pinnings. Let me know if you have questions.

**Comment by BastianZim** [comment]
Hi @wolfv thanks for the heads up, I just added this because I need it for a python package - my knowledge of cxx is close to nill so any help is much appreciated! 😄 

Based on the `coin-or`. packages I would expect this to be 

```yaml
run_exports:
  - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}
```

Correct? 

Problem is that I'm not sure how tight they're supposed to be, I guess I need to ask upstream, right?

Just because it's slightly related to this issue: Should the package also be added to conda-forge pinning?
